# example netlify.toml
[build]
command = "npm run build"
functions = "functions"
publish = "/dist"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[context.development_netlify-forms.environment]
VUE_APP_DEPLOY_BRANCH = "https://development-netlify-forms--tinnitus-project-by-ed-01-2021.netlify.app"
NODE_ENV = "production"

[dev]
framework = "#custom"
command = "npm run serve"
targetPort = 8080
port = 4000
autoLaunch = true
